### ISSUE TITLE
Trained Perfection should not get consumed by Innovation

### ISSUE THREAD

**Issue by pruik** [dazemc/ffxiv-craft#24]
The new Trained Perfection buff reduces the next Durability cost to 0. In the game, this buff does not get consumed if the next action already costs 0 durability (such as Innovation/Veneration)

**Comment by dazemc** [comment]
Did you get a macro solution that had trained perfection before either of those? I have it set to only prepend groundwork or preparatory touch so unless something is wrong... 
It still needs to be updated for manual entry but I'm currently working on specialist stuff

**Comment by Lynith1** [comment]
> Did you get a macro solution that had trained perfection before either of those? I have it set to only prepend groundwork or preparatory touch so unless something is wrong... It still needs to be updated for manual entry but I'm currently working on specialist stuff

I don't think the solver ever puts it before those actions, but by not doing so it's leaving out important combos.  For example:
MM + TP + Ven + Groundwork + Groundwork + Delicate + Delicate + Progress
is a valid opener vs what the solver gives which is
MM + Ven + TP + Groundwork + Groundwork + Delicate  + Ven + Delicate + Progress

Otherwise, everything else I've tested has been great!

**Comment by dazemc** [comment]
Just pushed an update to resolve this, if it looks good I'll close this issue

**Comment by dazemc** [comment]
I also made it so that trained perfection doesn't count as a wasted action and actually decreases action count, because it basically does, in an attempt to get the algo to favor it
