### ISSUE TITLE
What happened to the craft optimizer?

### ISSUE THREAD

**Issue by jimtheviking** [dazemc/ffxiv-craft#40]
Entire thing seems to have been overwritten by parallels desktop.

**Comment by Ultimatonium** [comment]
no idea what happend. maybe he got hacked, made mistake or just wanted to get rid off this project.
anyway I made my own fork of the last version before everything got deleted (b7499ba33bfa66bb6b3c37c626bb260ec98ce03b).
it's just a straight up copy and because i have no idea what i'm doing i have no plans of updating or suporting anything. 
atm it seems to be working so feel free to use it but dont expect anything from me :)

https://ultimatonium.github.io/FFXIV-Crafting-Optimizer/

**Comment by jimtheviking** [comment]
Thanks for the heads up!

**Comment by dazemc** [comment]
Yes had a session hijack recently and been going through changing passwords and revoking sessions on all my accounts. This should be fine now. Haven't taken security seriously until recently!
